server:
  port: 8059

spring:
  activiti:
    check-process-definitions: true #启动时不检查流程文件
  application:
    name: activiti
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    name: datasource
    initialize: true
    url: ${datasource.url:jdbc:mysql://192.168.1.246:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${datasource.username:root}
    password: ${datasource.password:sBtbGSMw}
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource